spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio_db
    username: postgres
    password: postgres999

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: lakshmilj555@gmail.com
    password: jxtbotmnhqbhqjda
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  port: 8080